In [ ]:
# Model-Based RL with Learned Transition Function f_\theta(s, a)
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
class GridWorld4x4:
    def __init__(self):
        self.nS = 16  # 4x4 grid
        self.nA = 4   # up, down, left, right
        self.P = self._build_transition_model()
        self.r = self._build_reward_model()
        self.gamma = 0.99

    def _build_transition_model(self):
        # NOTE true transition model (not used in planning, only for generating data)
        P = np.zeros((self.nS, self.nA, self.nS))
        for s in range(self.nS):
            x, y = s // 4, s % 4
            next_states = [
                (max(x-1,0), y),  # up
                (min(x+1,3), y),  # down
                (x, max(y-1,0)),  # left
                (x, min(y+1,3))   # right
            ]
            for a, (nx, ny) in enumerate(next_states):
                ns = nx * 4 + ny
                P[s, a, ns] = 1.0
        return P

    def _build_reward_model(self):
        ##########################################
                #YOUR CODE HERE
        ##########################################
        return R;

    def sample_transition(self, s, a):
        probs = self.P[s, a]
        return np.random.choice(self.nS, p=probs)

In [ ]:
class TransitionModel(nn.Module):
    def __init__(self, nS, nA):
        super().__init__()
        self.model = nn.Sequential(
            #######################################
                  #####YOUR CODE HERE
            ########################################
        )

    def forward(self, s, a):
        x = torch.cat([s, a], dim=-1)
        return self.model(x)

def one_hot(index, size):
    vec = np.zeros(size)
    vec[index] = 1.0
    return vec

def collect_data(env, N=1000):#Try out with 100 samples and 1000 samples
    D = []
    for _ in range(N):
        s = np.random.randint(env.nS)
        a = np.random.randint(env.nA)
        s_next = env.sample_transition(s, a)
        D.append((s, a, s_next))
    return D

def train_dynamics_model(data, nS, nA, epochs=10): #Increase epochs if required
    model = TransitionModel(nS, nA)
    optimizer = optim.Adam(model.parameters(), lr=5e-1)
    loss_fn = nn.MSELoss()

    for epoch in range(epochs):
        total_loss = 0
        for s, a, s_next in data:
            #########################################################
                  #####YOUR CODE HERE
            #########################################################
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

    return model

In [ ]:
def rollout_and_plan(env, model, R, gamma, n_rollouts=100):
    Q = np.zeros((env.nS, env.nA))
    with torch.no_grad():
        for s in range(env.nS):
            ###########################################
                  #####YOUR CODE HERE
            ###########################################
    # Greedy policy
    policy = np.argmax(Q, axis=1)
    return policy

In [ ]:
if __name__ == "__main__":
    env = GridWorld4x4()
    data = collect_data(env, N=5000)
    model = train_dynamics_model(data, env.nS, env.nA, epochs=20)
    policy = rollout_and_plan(env, model, env.r, env.gamma)

    print("Learned Policy (0=up, 1=down, 2=left, 3=right):")
    print(policy.reshape(4, 4))


Epoch 1, Loss: 9816.6372
Epoch 2, Loss: 9426.3986
Epoch 3, Loss: 9373.0095
Epoch 4, Loss: 9372.9878
Epoch 5, Loss: 9372.9850
Epoch 6, Loss: 9430.1976
Epoch 7, Loss: 9403.3376
Epoch 8, Loss: 9372.9857
Epoch 9, Loss: 9372.9849
Epoch 10, Loss: 9372.9848
Epoch 11, Loss: 9372.9848
Epoch 12, Loss: 9372.9848
Epoch 13, Loss: 9623.9218
Epoch 14, Loss: 9455.9850
Epoch 15, Loss: 9455.9848
Epoch 16, Loss: 9455.9848
Epoch 17, Loss: 9455.9848
Epoch 18, Loss: 9399.0942
Epoch 19, Loss: 9372.9848
Epoch 20, Loss: 9372.9848
Learned Policy (0=up, 1=down, 2=left, 3=right):
[[3 1 1 1]
 [0 3 1 1]
 [3 1 1 1]
 [3 1 3 1]]
